### ISSUE TITLE
EventLog 0.0.13 on MC 0.4.5-a

### ISSUE THREAD

**Issue by veitw** [ryanblenis/MeshCentral-EventLog#2]
Hi Ryan,

thank you for your plugin! 

After updating MC to 0.4.5-a and EventLog to 0.0.13, the log history is empty. However live logs are displayed.

Is this a bug or do I need to do something to complete the update, e.g. somehow update the event database schema?

Best regards,
// Veit

**Comment by ryanblenis** [comment]
Hi @veitw ,

Thanks for the report! The upgrade process changed a few identifiers, which hid old event data. I've created a new DB upgrade process that is available in v0.0.14 and will bring back your old data.

The event history is rotating on a 30 day rotation (events older than 30 days will be removed periodically to keep the database slim), so it would have worked itself out, but I don't like the sudden loss of data.

Note that 0.0.14 currently has an upgrade issue that should be resolved by [this](https://github.com/Ylianst/MeshCentral/pull/690) pull request to the MeshCentral project.

**Comment by ryanblenis** [comment]
Note: the PR was accepted, and will be in the next release when Ylian makes it

**Comment by ryanblenis** [comment]
Just want to confirm the latest version corrects this. Please let me know. Thank you

**Comment by veitw** [comment]
Hi Ryan, 

I had no possibility to test so far. I expect to be able to test it on Monday. 

Thanks and best regards, 
// Veit

**Comment by veitw** [comment]
Hi @ryanblenis,

> Just want to confirm the latest version corrects this. Please let me know. Thank you

unfortunately, the update did not help; I updated EventLog to 0.0.15 via MC2->My Server->Plugins->EventLog->Upgrade and updated the core, but the event history stays empty for agent users. I also updated MC2 to 0.4.5-c, restarted MC2 and waited 30 minutes, but that did not help either.

As also no new data is logged into the event history, I think the database schema still does not match. May I simply stop MC, delete the plugin-eventlog-events.db and start MC? We do not cling to the historical data itself, but it would be nice to have more that just the live view.

Best regards,
// Veit

**Comment by ryanblenis** [comment]
Hi @veitw,

Sorry to hear the update didn't help. You can indeed delete the plugin-eventlog-events.db at any time and a new one will be created. 

Before doing so, the events that are queried from the endpoints store a reference to the last time of a successful extraction. Can you update one or two of the endpoints from the console by issuing the command "dbset pluginEventLog_lvdoc 0" and waiting 2-3 minutes to see if the history for that endpoint comes back?

This command essentially sets the last collected event time to "never" and restarts the process with the last 200 event logs. Otherwise new events should still be populating.

Please let me know your findings, and I will update the interface to have a method to reset all endpoints so this does not have to be done manually for all of them. Thank you.

**Comment by veitw** [comment]
Hi @ryanblenis,
  
I issued

    dbset pluginEventLog_lvdoc 0

to two clients and both replied with

    Key set: 1

I have waited for 10 minutes but no data appeared in the plugin's History tab.

If you have another idea; I have not yet removed the DB.

Best regards,
// Veit

**Comment by ryanblenis** [comment]
Hi @veitw,

Can you check the value on that endpoint with "dbget pluginEventLog_lvdoc"? If it is still 0 then the collection has not occurred. If it is a larger number (Unix timestamp) then it has indeed run.

Also, you can alter the /modules_meshcore/eventlog.js so that the "var debug_flag = false;" (line 15) is true- then push the core again to the machine(s) we're testing on. This will output an "eventlog.txt" with some diagnostic data in the Mesh Agent directory, and create several "psoutXXXXX.txt" files (where XXXXX is a random string) showing the PowerShell that is attempting to be executed.

You may re-run those commands manually (as an admin) on those system(s) to see if PowerShell produces any kind of error. Please note issue #1 and the requirements for PowerShell to effectively collect event logs. Please post back your findings! Thank you.

**Comment by veitw** [comment]
Hi @ryanblenis,

this one is interesting:

I am testing against two machines of identical hardware that behave differently but should, except for a few specialised applications, be set-up identically (automatic Windows 10 networked installation and configuration through our software deployment system) and are both completely up to date against both our software and configuration repository and WSUS. Also the both machines are quite fresh and have just recently been installed (October 2019). The only major difference is that one machine is from the first batch where we realised later that the Windows-Update-supplied graphics driver did not support 3 displays at once and the Windows-Update-supplied NIC driver did not support Wake-on-LAN, so this machine received vendor drivers via our software deployment **after** set-up of Windows, but the other machine during Windows set-up instead.

System A (the one with driver installation after Windows set-up):

    > dbget pluginEventLog_lvdoc
    0

But in the meantime, new events showed up in the Live tab.

System B (driver installation during Windows set-up):

    > dbget pluginEventLog_lvdoc
    1575451465

This matches the local time of the last event that is shown in the Live tab when the Unix timestamp is evaluated as GMT (read: the Unix timestamp includes the local timezone offset of the agent, and I think it should not, as the MC user evaluating the logs might be in a different time zone than the agent device user):

    $ perl -e 'print scalar gmtime 1575451465'
    Wed Dec  4 09:24:25 2019

I will try ask the users for their support and debug the agent later.

The History tabs of both machines remain empty.

Best regards,
// Veit

**Comment by ryanblenis** [comment]
Hi @veitw ,

1. Have you updated to the latest version of the plugin (0.0.17)? It fixes several issues.

2. The "lvdoc" value is used to narrow the scope of collected events, so it uses minimal processing power when collecting new events, so it should not matter which TZ it is stored in.

3. I see what you mean about TZ's from the admin's perspective. I should make a note that all timestamps are local to the endpoint and/or have a conversion for the admin user.

4. Are there any errors in the browsers console for you when switching to a device within MeshCentral?

**Comment by ryanblenis** [comment]
Hi @veitw,

Just wanted to check in here and see if everything was resolved in the new versions.

**Comment by veitw** [comment]
Hi @ryanblenis,

thanks for asking. Unfortunately I had no time to work on this until
now. I am positive to be able to do so early next week.

Best regards,
// Veit

**Comment by veitw** [comment]
Hi @ryanblenis,

>     1. Have you updated to the latest version of the plugin (0.0.17)? It fixes several issues.

yes, we already did.

After updating, we executed the agent core refresh using the button on the yellow bar as seen here:
![grafik](https://user-images.githubusercontent.com/16285895/70546474-a1514880-1b6f-11ea-9295-96564b959723.png)

>     4. Are there any errors in the browsers console for you when switching to a device within MeshCentral?

Unfortunately I am unable to verify this, as EventLog eventually has stopped working compeltely; one can open the settings, but the endpoints' plugin tabs are empty:
![grafik](https://user-images.githubusercontent.com/16285895/70549071-eb3c2d80-1b73-11ea-97f9-de84bb2a65f9.png)

I need to have a look into this when I am less busy. :/
At least the JS console keeps clear.

**Comment by ryanblenis** [comment]
Wow, the tab isn't even there in that screenshot! And the latest version info hasn't popped up for you. What version of MeshCentral is this running, I'll want to test- but it should be compatible because it allowed you to install that version of the plugin, but something is definitely going on here. Interested in your findings and happy to help whenever you have time.

**Comment by veitw** [comment]
MC is 0.4.5-c and can currently not be updated.

New plugin version never pops up for us, I blame MC's auto-update feature on this, which we disabled. But I am not sure with this. Though, MC downloads and installs new plugin versions when the upgrade option is run.

**Comment by veitw** [comment]
Hi @ryanblenis,

I informed all users of an update and updated MC to 0.4.5-p.

After upgrading the plugin *again* to 0.0.17, it came back to live and now also shows the history for some devices and I am positive that all devices will have their event history back soon :)

Best regards,
// Veit

**Comment by ryanblenis** [comment]
That's great news!

Odd that you were at 0.0.17 on 0.4.5-c, as 0.0.17 was for -e or greater- so that could explain some things with it not working, but not how you upgraded to 0.0.17 in the first place!
As far as I know, plugins are not automatically upgraded with the MC upgrade process.

Glad to hear it is now working as expected. Please let me know if you have any other issues. Thank you.
