### ISSUE TITLE
[Question]:: Alerts on logs

### ISSUE THREAD

**Issue by openmoto** [ryanblenis/MeshCentral-EventLog#5]
Hi @ryanblenis,
First of all, thanks for your great work here.
Been using meshcentral side by side with an RMM tool and faithfully waiting for the day I don't have to carry the monthly charges just to help friends. So seeing your eventlog and scripts plugin was a huge relief.

I have a question though.
I have a few scripts to check and alert on specific Event IDs on windows computers and since you can already read logs with this plugin, I was wondering if there's a chance that this plugin could be extended to send alerts when a specific even ID is seen.

Ideally, when setting up the alerts, one can select which meshcentral user or user group to send the alert to.

Alternatively, perhaps having custom fields in the scripts plugin that can pass values to power-shell scripts might help? That way, each script doesn't have to be re-written per group?

Thanks

**Comment by ryanblenis** [comment]
Hi @openmoto,

Actually this is already underway, but not in just an EventLog way...
I've been tossing up how I want this integration to work for some time now across my plugins, but I have been working on monitoring and alerting for a while, which will integrate with both EventLog and ScriptTask (e.g. monitor for an event ID, trigger a script to run as a result). There are, as you can imagine, a lot of moving parts that go into this, but the new plugin will integrate with the Zabbix API (or at least leverage the zabbix agent) for monitoring purposes (because it's super lightweight and can monitor almost ANYTHING). While I am scoping down what Zabbix can do through the MeshCentral interface (because rewriting the whole Zabbix front-end to integrate with MeshCentral would take a LONG time), so if Zabbix is used, you can go directly into Zabbix and set up additional monitors, but basic ones will be available in the MeshCentral interface and grow over time.

As you can imagine, this isn't a small task, and I'm doing this in my spare time, but rest assured, it is coming. Also coming down the line are procedure based scripts that introduce logic to the scripting process at a higher level, variable substitution, and script reactions (to take place based on the return value of scripts). 

For now, I can recommend that (assuming you have a domain for each case / customer you're working with) that you get that via powershell and use that to dictate logic in the script versus creating a new script per group. Would that work?

**Comment by openmoto** [comment]
Thanks,
I'm happy with what's available at the moment but glad to hear what you have planned..
I agree it's no small task especially working on this on your spare time!
Actually just using meshcentral to support friends and family at the moment, but I no longer pay for RMM for managing friend's computers. 

As per your suggestion, yes. I can see that working for domain computers. Script can have build in checks, if the domain is this, then variable set equals that. 

Alternatively, one could create a script per group that creates a registry key and adds a value to it, This could be owner information, including email. This script can be scheduled to run weekly or so making sure the value is always correct.
Then instead of checking the domain, to set the correct variables, your new scripts can just pull the value from the registry when it runs. I've done something similar in the past.

Anyways, this is more of something I think would be useful than something I need.
I'm not a programmer but getting better at powershell, so if you need something tested, of have a powershell question, I'll be glad to help if it's not above my skill level. You're doing all the heavy lifting already!
